In [1]:
import pandas as pd
import numpy as np
from path import Path
from sklearn import tree
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
from sklearn.ensemble import RandomForestClassifier

C:\Users\Sami_\anaconda3\envs\mlenv\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)


In [2]:
# Loading data
file_path = Path("../Resources/loans_data_encoded.csv")
df_loans = pd.read_csv(file_path)
df_loans.head()

amount  term  age  bad  month_num  education_Bachelor  \
0    1000    30   45    0          6                   0   
1    1000    30   50    0          7                   1   
2    1000    30   33    0          8                   1   
3    1000    15   27    0          9                   0   
4    1000    30   28    0         10                   0   

   education_High School or Below  education_Master or Above  \
0                               1                          0   
1                               0                          0   
2                               0                          0   
3                               0                          0   
4                               0                          0   

   education_college  gender_female  gender_male  
0                  0              0            1  
1                  0              1            0  
2                  0              1            0  
3                  1              0            1  
4                  1              1            0

In [21]:
X=df_loans.copy()
X=X.drop(["bad","education_Bachelor","education_High School or Below","education_Master or Above", "education_college", "gender_female", "gender_male"],axis=1)

In [22]:
# Define the target set.
y = df_loans["bad"].ravel()
y[:5]

array([0, 0, 0, 0, 0], dtype=int64)

In [23]:
X_train, X_test, y_train, y_test = train_test_split(X,y,random_state=78)

In [24]:
scaler = StandardScaler()

#fit the standard scaler with training data
X_scaler = scaler.fit(X_train)

#scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

print(np.mean(X_train_scaled[:,0]))
print(np.mean(X_test_scaled[:,0]))
print(np.std(X_train_scaled[:,0]))
print(np.std(X_test_scaled[:,0]))


3.931669804539221e-16
0.08040483006321758
1.0
0.8450480061575104


In [25]:
# Create a random forest classifier.
rf_model = RandomForestClassifier(n_estimators = 500, random_state=78)

rf_model = rf_model.fit(X_train_scaled, y_train)

#Making predictions using the testing data.
predictions = rf_model.predict(X_test_scaled)
predictions

array([1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0,
       1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1], dtype=int64)

In [26]:
# Calculating the confusion matrix
cm = confusion_matrix(y_test, predictions)


# Create a DataFrame from the confusion matrix.

cm_df = pd.DataFrame(
cm, index=["Actual 0","Actual 1"], columns=["Predicted 0", "Predicted 1"])

cm_df

Predicted 0  Predicted 1
Actual 0           51           33
Actual 1           25           16

In [27]:
#calculate accuracy score
acc_score = accuracy_score(y_test, predictions)
acc_score

0.536

In [28]:
# Displaying results
print("Confusion Matrix")
display(cm_df)
print(f"Accuracy Score : {acc_score}")
print("Classification Report")
print(classification_report(y_test, predictions))

Confusion Matrix


Predicted 0  Predicted 1
Actual 0           51           33
Actual 1           25           16

Accuracy Score : 0.536
Classification Report
              precision    recall  f1-score   support

           0       0.67      0.61      0.64        84
           1       0.33      0.39      0.36        41

    accuracy                           0.54       125
   macro avg       0.50      0.50      0.50       125
weighted avg       0.56      0.54      0.55       125



In [29]:
#calculate feature importance for RF model
importances = rf_model.feature_importances_
importances

array([0.05961604, 0.09864621, 0.50218612, 0.33955162])

In [30]:
sorted(zip(rf_model.feature_importances_,X.columns), reverse=True)

[(0.5021861245304408, 'age'),
 (0.33955161660229205, 'month_num'),
 (0.09864621418980625, 'term'),
 (0.059616044677461004, 'amount')]